add configuration option for flags
benvp/insomnia-plugin-op pull request #3
Opened 2024-09-03 08:25 UTC by Kasi07

As I have two accounts in my 1Password vault, I couldn't receive any secrets.
So I added a “flags” config to configure [1Password global flags](https://developer.1password.com/docs/cli/reference/#global-flags).

2024-09-04 08:45 UTC, benvp requested changes
Tahnks! Just a minor thing.

In addition, we should look into how this is possible when using https://github.com/benvp/insomnia-plugin-op/issues/2 the one password sdk

2024-09-04 08:45 UTC, benvp commented on src/app.ts
> +  flags?: {};
Can you change that type to e.g. `Record<string, any>`? Using `{}` as a type means that this is an object without any keys assigned to it.

2024-09-25 14:16 UTC, shadi-sharaf-nuk commented
Thanks [Kasi07](https://github.com/Kasi07)! I was just going to PR the change myself and I'm happy to have checked the pull-requests first :D 

Thanks @benvp for the quick review, would really love to have this change released!

2024-10-24 19:53 UTC, benvp approved these changes

2024-10-24 19:53 UTC, merged

2024-10-24 20:25 UTC, benvp commented
Sorry for the delay. Didn't have any time yet. Just released 0.2.0. And thanks for your contribs!